project:
  type: book
  output-dir: docs

book:
  title: "Znanost o podacima u R-u"
  author: "Alen Husnjak"
  date: "2/5/2026"
  chapters:
    - part: index.qmd
    - part: "Uvod u znanost o podacima"
      chapters:
        - 01_01_uvod_u_znanost_o_podacima.qmd
    - part: "Uvoz i ureÄ‘ivanje podataka"
      chapters:
        - 02_01_uvoz_podataka.qmd
        - 02_02_uredivanje_podataka.qmd
    - part: 03_00_transformacija_podataka.qmd
      chapters:
        - dplyr.qmd
        - 03_01_manipulacija_podacima.qmd
        - 03_02_nedostajajuce_vrijednosti.qmd
        - 03_03_pridruzivanje_podataka.qmd
        - 03_04_brojevi.qmd
        - 03_05_logicke_vrijednosti.qmd
        - 03_06_faktori.qmd
        - 03_07_nizovi.qmd
        - 03_08_regularni_izrazi.qmd
        - 03_09_datum_i_vrijeme.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    toc: true
    code-tools: true
    css: styles.css
    theme:
      - cosmo
      - brand
