project:
  type: book
  output-dir: docs

book:
  title: "Znanost o podacima u R-u"
  author: "Alen Husnjak"
  date: "2/5/2026"
  chapters:
    - index.qmd
    - part: "Uvod u znanost o podacima"
      chapters:
        - 01_uvod_u_znanost_o_podacima.qmd
    - part: "Uvoz i ureÄ‘ivanje podataka"
      chapters:
        - 02_uvoz_podataka.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    toc: true
    number-sections: true
    code-fold: true
    code-tools: true
    css: styles.css
    theme:
      - cosmo
      - brand
